trigger:
  - 'build'

pool:
    vmImage: 'ubuntu-latest'

variables:


  steps:
    - task: UseDotNet@2
      displayName: 'Setup .NET SDK $$($dotnatSdkVersion)'
      inputs:
        version: '$(dotnetSdkVersion)'

    - task: DotNetCoreCLI@2
      displayName: 'Build Azure Functions Counter'
      inputs:
        command: 'build'
        arguments: '--configuration'
        projects: 'backend/api'
        



