trigger:
  branches:
    include:
      - master  # Change this to your main branch name
  paths:
    include: 
      - frontend/*
    exclude:
      - frontend/cv/*   
      
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/frontend/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'
  displayName: 'Copy Files from Frontend folder'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/dist'
    artifactName: 'website'
    publishLocation: 'Container'
  displayName: 'Publish Artifact from frontend'

- task: CopyFiles@2
  inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/backend/infra'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/dist/infra'
  displayName: 'Copy Files from infra folder'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/dist/infra'
    artifactName: 'iac-infra'
    publishLocation: 'Container'
  displayName: 'Publish Artifact from infra'