trigger:
  paths:
    include:
      - frontend/cv

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/frontend/cv'
    Contents: '.pdf'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Files from CV folder'
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'cv'
    publishLocation: 'Container'
  displayName: 'Publish Artifact from CV folder'

